# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170208_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topup',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
