# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20170208_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('v', 'valid'), ('i', 'invalid')], max_length=1),
        ),
    ]
